Repository maxellmilay/finite-automata-visualizer, pull requests merged in 2024-06, with the labels that each got.

#29 add animation, item delete and share, and fix stuff
  app/page.tsx
  components/CircleNode.tsx
  components/DFA.tsx
  components/FloatingEdge.tsx
  components/LegendPanel.tsx
  components/SelfConnectingEdge.tsx
  components/SidePanel.tsx
  components/SidePanelItem.tsx
  interfaces/graph.ts
  interfaces/store.ts
  store/dfaStore.ts
  styles/global.scss
  styles/sidepanelItem.scss
  utils/db.ts
Labels: best fking programmer🔥

#50 Make Splash Screen responsive
  components/SplashScreen.tsx
  styles/splashscreen.scss
Labels: enhancement

#61 Create coachmarks
  app/layout.tsx
  app/page.tsx
  components/LegendPanel.tsx
  components/SidePanel.tsx
  components/WelcomeModal.tsx
  constants/demo.ts
  package-lock.json
  package.json
  public/images/logo.svg
  styles/global.scss
Labels: neal rigga
